### ISSUE TITLE
Matching Issue - New Sensations

### ISSUE THREAD

**Issue by dappleyard** [PAhelper/PhoenixAdult.bundle#908]
Some files seem to match on URL, but many fail - Log below
```
2020-07-28 08:08:51,437 (2ca4) :  INFO (logkit:16) - *******MEDIA TITLE****** Newsensations Raven Rockette Hope Howell Lesbians and Their Big Toys
2020-07-28 08:08:51,437 (2ca4) :  INFO (logkit:16) - Getting Search Settings for: Newsensations Raven Rockette Hope Howell Lesbians and Their Big Toys
2020-07-28 08:08:51,437 (2ca4) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Newsensations Raven Rockette Hope Howell Lesbians and Their Big Toys
2020-07-28 08:08:51,447 (2ca4) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Newsensations Raven Rockette Hope Howell Lesbians and Their Big Toys
2020-07-28 08:08:51,448 (2ca4) :  INFO (logkit:16) - Site found with method #3
2020-07-28 08:08:51,448 (2ca4) :  INFO (logkit:16) - ^^^^^^^ siteID: 280
2020-07-28 08:08:51,448 (2ca4) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-07-28 08:08:51,448 (2ca4) :  INFO (logkit:16) - newsensations  vs new sensations
2020-07-28 08:08:51,448 (2ca4) :  INFO (logkit:16) - 3
2020-07-28 08:08:51,450 (2ca4) :  INFO (logkit:16) - 8
2020-07-28 08:08:51,450 (2ca4) :  INFO (logkit:16) - searchTitle (before date processing): Raven Rockette Hope Howell Lesbians and Their Big Toys
2020-07-28 08:08:51,450 (2ca4) :  INFO (logkit:16) - Search Title: Raven Rockette Hope Howell Lesbians and Their Big Toys
2020-07-28 08:08:51,450 (2ca4) :  INFO (logkit:16) - Raven%20Rockette%20Hope%20Howell%20Lesbians%20and%20Their%20Big%20Toys
2020-07-28 08:08:51,450 (2ca4) :  INFO (logkit:16) - Using Google Search "site:www.newsensations.com Raven Rockette Hope Howell Lesbians and Their Big Toys"
2020-07-28 08:08:54,096 (2ca4) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Raven-Rockette-Hope-Howell-Lesbians-and-Their-Big-Toys.html"
2020-07-28 08:08:55,197 (2ca4) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Raven-Rockette-Hope-Howell-Lesbians-and-Their-Big-Toys-.html"
2020-07-28 08:08:55,526 (2ca4) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/dvds/Raven-Rockette-Hope-Howell-Lesbians-and-Their-Big-Toys.html"
2020-07-28 08:08:55,874 (2ca4) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/dvds/LesbiansAndTheirBigToys.html"
2020-07-28 08:08:56,368 (2ca4) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_sos/dvds/LesbiansAndTheirBigToys.html"
2020-07-28 08:08:56,927 (2ca4) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'openSubtitlesHash': 'e1ae74a47f1e8f97', 'name': 'Newsensations Raven Rockette Hope Howell Lesbians and Their Big Toys', 'filename': 'Z%3A%5CNew%20Sensations%5CNewsensations-Raven-Rockette-Hope-Howell-Lesbians-And-Their-Big-Toys%2Emp4', 'plexHash': '8b44a3c345b43c90d7c33e8a483ff86760c67518', 'duration': '2337878', 'id': '88479'} (most recent call last):
  File "E:\Program Files (x86)\Plex\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\david\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 798, in search
    results = PAsearchSites.siteVRConk.search(results, encodedTitle, searchTitle, siteNum, lang, searchDate)
  File "C:\Users\david\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteNewSensations.py", line 25, in search
    titleNoFormatting = searchResult.xpath('(//div[@class="trailerVideos clear"] | //div[@class="dvdSections clear"])/div[1]')[0].text_content().replace('DVDS /', '').strip()
  File "E:\Program Files (x86)\Plex\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2020-07-28 08:08:56,927 (2ca4) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-07-28 08:08:56,927 (2ca4) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by DirtyRacer1337** [comment]
Fixed in 9683aed7d9fc18fc5b4fe0f91d4923bef596ec6e

**Comment by dappleyard** [comment]
Thanks for this it has solved some of the issues, but there are some of the scenes that don't have a single hyphen between words in the URL   - https://www.newsensations.com/tour_ns/updates/Scarlet-Red--Karla-Kush---Sisterly-Love-2.html  or https://www.newsensations.com/tour_ns/updates/Scarlet-Red---Almost-Relatives.html.

These ones still fail to match 

2020-07-29 06:55:08,348 (517c) :  INFO (logkit:16) - *******MEDIA TITLE****** Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:08,348 (517c) :  INFO (logkit:16) - Getting Search Settings for: Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:08,348 (517c) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:08,355 (517c) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:08,358 (517c) :  INFO (logkit:16) - Site found with method #3
2020-07-29 06:55:08,358 (517c) :  INFO (logkit:16) - ^^^^^^^ siteID: 280
2020-07-29 06:55:08,358 (517c) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-07-29 06:55:08,358 (517c) :  INFO (logkit:16) - newsensations  vs new sensations
2020-07-29 06:55:08,358 (517c) :  INFO (logkit:16) - 3
2020-07-29 06:55:08,358 (517c) :  INFO (logkit:16) - 8
2020-07-29 06:55:08,358 (517c) :  INFO (logkit:16) - searchTitle (before date processing): Scarlet Red Almost Relatives
2020-07-29 06:55:08,359 (517c) :  INFO (logkit:16) - Search Title: Scarlet Red Almost Relatives
2020-07-29 06:55:08,359 (517c) :  INFO (logkit:16) - Scarlet%20Red%20Almost%20Relatives
2020-07-29 06:55:08,359 (517c) :  INFO (logkit:16) - Using Google Search "site:www.newsensations.com Scarlet Red Almost Relatives"
2020-07-29 06:55:11,180 (517c) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Scarlet-Red-Almost-Relatives.html"
2020-07-29 06:55:11,640 (517c) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Scarlet-Red-Almost-Relatives-.html"
2020-07-29 06:55:12,104 (517c) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/dvds/Scarlet-Red-Almost-Relatives.html"
2020-07-29 06:55:12,638 (517c) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-07-29 06:55:12,638 (517c) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2020-07-29 06:55:38,242 (4c88) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo3ZjhjMmRkODVlMzVlM2QxczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczQyCk5ld3NlbnNhdGlvbnMgU2NhcmxldCBSZWQgQWxtb3N0IFJlbGF0aXZlc3M0Cm5hbWVzNzYKWiUzQSU1Q05ldyUyMFNlbnNhdGlvbnMlNUNOZXdzZW5zYXRpb25zLVNjYXJsZXQtUmVkLS0tQWxtb3N0LVJlbGF0aXZlcyUyRW1wNHM4CmZpbGVuYW1lczQwCjMyYzRjNWIwNGYzZTQzNTBhMWIzOGJmZjcyZjVmMDQ2YjExODNhMWNzOApwbGV4SGFzaHM3CjIwMDI4NDhzOApkdXJhdGlvbnM1Cjg4NDgwczIKaWRyMAo_
2020-07-29 06:55:38,242 (4c88) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-07-29 06:55:38,243 (4c88) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo3ZjhjMmRkODVlMzVlM2QxczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczQyCk5ld3NlbnNhdGlvbnMgU2NhcmxldCBSZWQgQWxtb3N0IFJlbGF0aXZlc3M0Cm5hbWVzNzYKWiUzQSU1Q05ldyUyMFNlbnNhdGlvbnMlNUNOZXdzZW5zYXRpb25zLVNjYXJsZXQtUmVkLS0tQWxtb3N0LVJlbGF0aXZlcyUyRW1wNHM4CmZpbGVuYW1lczQwCjMyYzRjNWIwNGYzZTQzNTBhMWIzOGJmZjcyZjVmMDQ2YjExODNhMWNzOApwbGV4SGFzaHM3CjIwMDI4NDhzOApkdXJhdGlvbnM1Cjg4NDgwczIKaWRyMAo_
2020-07-29 06:55:38,243 (4c88) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': '7f8c2dd85e35e3d1', 'name': 'Newsensations Scarlet Red Almost Relatives', 'filename': 'Z%3A%5CNew%20Sensations%5CNewsensations-Scarlet-Red---Almost-Relatives%2Emp4', 'plexHash': '32c4c5b04f3e4350a1b38bff72f5f046b1183a1c', 'duration': '2002848', 'id': '88480'}
2020-07-29 06:55:38,243 (4c88) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/88480/tree'
2020-07-29 06:55:38,249 (4c88) :  INFO (logkit:16) - *******MEDIA TITLE****** Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:38,249 (4c88) :  INFO (logkit:16) - Getting Search Settings for: Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:38,250 (4c88) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:38,257 (4c88) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Newsensations Scarlet Red Almost Relatives
2020-07-29 06:55:38,259 (4c88) :  INFO (logkit:16) - Site found with method #3
2020-07-29 06:55:38,259 (4c88) :  INFO (logkit:16) - ^^^^^^^ siteID: 280
2020-07-29 06:55:38,259 (4c88) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-07-29 06:55:38,259 (4c88) :  INFO (logkit:16) - newsensations  vs new sensations
2020-07-29 06:55:38,260 (4c88) :  INFO (logkit:16) - 3
2020-07-29 06:55:38,260 (4c88) :  INFO (logkit:16) - 8
2020-07-29 06:55:38,260 (4c88) :  INFO (logkit:16) - searchTitle (before date processing): Scarlet Red Almost Relatives
2020-07-29 06:55:38,260 (4c88) :  INFO (logkit:16) - Search Title: Scarlet Red Almost Relatives
2020-07-29 06:55:38,262 (4c88) :  INFO (logkit:16) - Scarlet%20Red%20Almost%20Relatives
2020-07-29 06:55:38,262 (4c88) :  INFO (logkit:16) - Using Google Search "site:www.newsensations.com Scarlet Red Almost Relatives"
2020-07-29 06:55:41,210 (4c88) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Scarlet-Red-Almost-Relatives.html"
2020-07-29 06:55:41,750 (4c88) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Scarlet-Red-Almost-Relatives-.html"
2020-07-29 06:55:42,339 (4c88) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/dvds/Scarlet-Red-Almost-Relatives.html"
2020-07-29 06:55:42,842 (4c88) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-07-29 06:55:42,842 (4c88) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2020-07-29 06:56:43,818 (66e0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgoyOGY2ZDJlMThhMjM5NzFiczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczUyCk5ld3NlbnNhdGlvbnMgU2NhcmxldCBSZWQgS2FybGEgS3VzaCBTaXN0ZXJseSBMb3ZlIDJzNApuYW1lczg3ClolM0ElNUNOZXclMjBTZW5zYXRpb25zJTVDTmV3c2Vuc2F0aW9ucy1TY2FybGV0LVJlZC0tS2FybGEtS3VzaC0tLVNpc3Rlcmx5LUxvdmUtMiUyRW1wNHM4CmZpbGVuYW1lczQwCjJkNTA2NzM3ZGVmNGE3MDNkMjNiNzk5MTE1NTk1OTVlZjMxODk3Y2RzOApwbGV4SGFzaHM3CjE2MTY1MDRzOApkdXJhdGlvbnM1Cjg4NDgxczIKaWRyMAo_
2020-07-29 06:56:43,819 (66e0) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-07-29 06:56:43,819 (66e0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgoyOGY2ZDJlMThhMjM5NzFiczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczUyCk5ld3NlbnNhdGlvbnMgU2NhcmxldCBSZWQgS2FybGEgS3VzaCBTaXN0ZXJseSBMb3ZlIDJzNApuYW1lczg3ClolM0ElNUNOZXclMjBTZW5zYXRpb25zJTVDTmV3c2Vuc2F0aW9ucy1TY2FybGV0LVJlZC0tS2FybGEtS3VzaC0tLVNpc3Rlcmx5LUxvdmUtMiUyRW1wNHM4CmZpbGVuYW1lczQwCjJkNTA2NzM3ZGVmNGE3MDNkMjNiNzk5MTE1NTk1OTVlZjMxODk3Y2RzOApwbGV4SGFzaHM3CjE2MTY1MDRzOApkdXJhdGlvbnM1Cjg4NDgxczIKaWRyMAo_
2020-07-29 06:56:43,819 (66e0) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': '28f6d2e18a23971b', 'name': 'Newsensations Scarlet Red Karla Kush Sisterly Love 2', 'filename': 'Z%3A%5CNew%20Sensations%5CNewsensations-Scarlet-Red--Karla-Kush---Sisterly-Love-2%2Emp4', 'plexHash': '2d506737def4a703d23b79911559595ef31897cd', 'duration': '1616504', 'id': '88481'}
2020-07-29 06:56:43,821 (66e0) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/88481/tree'
2020-07-29 06:56:43,825 (66e0) :  INFO (logkit:16) - *******MEDIA TITLE****** Newsensations Scarlet Red Karla Kush Sisterly Love 2
2020-07-29 06:56:43,826 (66e0) :  INFO (logkit:16) - Getting Search Settings for: Newsensations Scarlet Red Karla Kush Sisterly Love 2
2020-07-29 06:56:43,826 (66e0) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Newsensations Scarlet Red Karla Kush Sisterly Love 2
2020-07-29 06:56:43,835 (66e0) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Newsensations Scarlet Red Karla Kush Sisterly Love 2
2020-07-29 06:56:43,836 (66e0) :  INFO (logkit:16) - Site found with method #3
2020-07-29 06:56:43,836 (66e0) :  INFO (logkit:16) - ^^^^^^^ siteID: 280
2020-07-29 06:56:43,836 (66e0) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-07-29 06:56:43,836 (66e0) :  INFO (logkit:16) - newsensations  vs new sensations
2020-07-29 06:56:43,836 (66e0) :  INFO (logkit:16) - 3
2020-07-29 06:56:43,838 (66e0) :  INFO (logkit:16) - 8
2020-07-29 06:56:43,838 (66e0) :  INFO (logkit:16) - searchTitle (before date processing): Scarlet Red Karla Kush Sisterly Love 2
2020-07-29 06:56:43,838 (66e0) :  INFO (logkit:16) - Search Title: Scarlet Red Karla Kush Sisterly Love 2
2020-07-29 06:56:43,838 (66e0) :  INFO (logkit:16) - Scarlet%20Red%20Karla%20Kush%20Sisterly%20Love%202
2020-07-29 06:56:43,838 (66e0) :  INFO (logkit:16) - Using Google Search "site:www.newsensations.com Scarlet Red Karla Kush Sisterly Love 2"
2020-07-29 06:56:46,704 (66e0) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Scarlet-Red-Karla-Kush-Sisterly-Love-2.html"
2020-07-29 06:56:47,115 (66e0) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/updates/Scarlet-Red-Karla-Kush-Sisterly-Love-2-.html"
2020-07-29 06:56:48,582 (66e0) :  INFO (logkit:16) - Requesting GET "https://www.newsensations.com/tour_ns/dvds/Scarlet-Red-Karla-Kush-Sisterly-Love-2.html"
2020-07-29 06:56:49,098 (66e0) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-07-29 06:56:49,098 (66e0) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes

**Comment by DirtyRacer1337** [comment]
Try with this 05575e4aedf3c11f033bab576c9e0a5d3fded7b4
